### Register User
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Beatriz",
  "email": "beatriz@email.com",
  "password": "123456789"
}

### Login User
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "beatriz@email.com",
  "password": "123456789"
}

### Get User Data
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjhkYTAwZTZjZWFlMTZhMmFmYjg1NiIsImlhdCI6MTc0NzUyMTI5OSwiZXhwIjoxNzUwMTEzMjk5fQ.cJ6TlKrQqZiOsb-obHQvTPYl_xHvOQc5N6_PQUjugGU

### EDIT LOGGED USER
PATCH http://localhost:3000/api/auth/me
Authorization: Bearer <your_jwt_token_here>
Content-Type: application/json

{
  "name": "new_name_yey"
}

### DELETE LOGGED USER
DELETE http://localhost:3000/api/auth/me
Authorization: Bearer <your_jwt_token_here>
