### Register User
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "ADMIN",
  "email": "admin@email.com",
  "password": "123456789",
  "role": "admin"
}

### Login User
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "123456789"
}

### Get User Data
GET http://localhost:3000/api/auth/me
Authorization: Bearer <your_jwt_token_here>

### EDIT LOGGED USER
PATCH http://localhost:3000/api/auth/me
Authorization: Bearer <your_jwt_token_here>
Content-Type: application/json

{
  "name": "new_name_yey"
}

### DELETE LOGGED USER
DELETE http://localhost:3000/api/auth/me
Authorization: Bearer <your_jwt_token_here>


### ADMIN 


### GET ALL USERS 
GET http://localhost:3000/api/auth/
Authorization: Bearer <your_admin_jwt_token>


### GET USER BY ID
GET http://localhost:3000/api/auth/<user_id>
Authorization: Bearer <your_admin_jwt_token>

### update user 

PATCH http://localhost:3000/api/auth/<user_id>
Authorization: Bearer <your_admin_jwt_token>
Content-Type: application/json

{
  "name": "Updated Name",
  "location": "Porto, Portugal"
}


### delete user by id
DELETE http://localhost:3000/api/auth/<user_id>
Authorization: Bearer <your_admin_jwt_token>
